version: '3'

services:
    php:
        container_name: php-app
        build: php
        image: php:app
        ports:
          - 9000:9000
          - 9002:9001
        volumes:
            - ../app:/var/www/app
            - ./php/config/others.ini:/usr/local/etc/php/conf.d/others.ini
        networks:
            - app-network
        env_file:
            - ../app.env
    nginx:
        container_name: nginx-app
        build: nginx
        image: nginx:app
        ports:
          - 80:80
        volumes:
            - ../app:/var/www/app
            - ./nginx/logs/:/var/log/nginx
            - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/config/symfony.conf:/etc/nginx/sites-available/app.conf
        networks:
            - app-network
        env_file:
            - ../app.env
    mysql:
        container_name: mysql-app
        build: mysql
        image: mysql:app
        ports:
            - 6603:3306
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/conf.d:/etc/mysql/conf.d
            - ./mysql/init:/docker-entrypoint-initdb.d
        networks:
            - app-network
        env_file:
            - ../app.env
    phpmyadmin:
        container_name: phpmyadmin-app
        build: phpmyadmin
        image: phpmyadmin:app
        ports:
            - 8181:80
        networks:
            - app-network
        env_file:
            - ../app.env
        restart: always
    node:
        container_name: node-app
        build: node
        image: node:app
        tty: true
        volumes:
            - ../app:/var/www/app
        networks:
            - app-network
        ports:
          - 3000:3000

networks:
    app-network:
        driver: bridge